      1          ilftl
      4          ilfth
      5          irgtl
     24          irgth
     16          nkx  
     16          nky  
     16          nkz  
   4096          nk   
     24          nb   
      1          nbl  
     24          nbh  
     24          nband
      4          nbv  
     20          nbc  
      8          ngx  
      8          ngy  
      8          ngz  
    512          ng   
    512          nx   
